### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ahwm** [iigo-panel/iigo-panel#1]
- [ ] ~~Disk cleanup ?~~
- [ ] IIS Site browsing
- [ ] Install updates
- [ ] Website configuration (web.config, similar interface to IIS) ?
- [x] Disk usage (space free/used) in stats
- [ ] App Pool Monitor
- [ ] REST API
